[theme]
primaryColor = "rgb(92, 228, 136)"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f6fc"
linkColor = "#58a6ff"
borderColor = "#30363d"
showWidgetBorder = true
baseRadius = "0.375rem"
font = "sans-serif"
headingFont = "sans-serif"
codeFont = "monospace"
codeBackgroundColor = "#21262d"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#161b22"
secondaryBackgroundColor = "#21262d"

[browser]
gatherUsageStats = false